# Generated by Django 3.2.16 on 2024-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webloguser',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='Блокировка пользователя'),
        ),
    ]
