# Generated by Django 3.2.16 on 2024-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_webloguser_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='webloguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
