# Generated by Django 3.2.16 on 2024-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_webloguser_is_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webloguser',
            options={},
        ),
        migrations.AlterField(
            model_name='webloguser',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='блокировка'),
        ),
    ]
