# Generated by Django 3.2.16 on 2024-07-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240715_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webloguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
